const icons = {
  phone:'<path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.9a2 2 0 0 1-.5 2.1L8 10a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.5c.9.3 1.9.6 2.9.7a2 2 0 0 1 1.7 2z"/>',
  pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
  clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 3"/>',
  calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18M7 14h2m3 0h2m3 0h1M7 17h2m3 0h2"/>',
  arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',
  search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
  shield:'<path d="m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6l9-4Z"/><path d="m8 12 3 3 5-6"/>',
  heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
  cross:'<path d="M9 3h6v6h6v6h-6v6H9v-6H3V9h6V3Z"/>',
  users:'<circle cx="12" cy="7" r="3"/><path d="M6 21v-3a6 6 0 0 1 12 0v3H6ZM5 5a3 3 0 0 0 0 6m14-6a3 3 0 0 1 0 6M4 14a4 4 0 0 0-2 4v2m18-6a4 4 0 0 1 2 4v2"/>',
  message:'<path d="M21 11.5a9 9 0 0 1-9 9 10 10 0 0 1-4-.8L3 21l1.3-5a9 9 0 1 1 16.7-4.5Z"/><path d="M8 11h.01M12 11h.01M16 11h.01"/>',
  book:'<path d="M12 5c-3-3-7-3-10-2v16c4-1 7-1 10 2 3-3 6-3 10-2V3c-3-1-7-1-10 2Zm0 0v16"/>',
  file:'<path d="M14 2H5a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h14V7l-5-5Zm0 0v6h5M7 12h6m-6 4h3"/><circle cx="16" cy="17" r="3"/><path d="m18 19 3 3"/>',
  money:'<rect x="5" y="2" width="14" height="20" rx="2"/><path d="M12 6v12m3-10h-4a2 2 0 0 0 0 4h2a2 2 0 0 1 0 4H9"/>',
  menu:'<path d="M4 6h16M4 12h16M4 18h16"/>'
};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.cross}</svg>`;}
function renderIcons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));}
const specialties=[
 {name:'Khám bệnh tổng quát',desc:'Chủ động chăm sóc sức khỏe mỗi ngày',image:'55d1223a1ac3ed1d.png',details:'Thăm khám ban đầu và tư vấn chuyên khoa phù hợp với nhu cầu của người bệnh.'},
 {name:'Sản – Phụ khoa',desc:'Đồng hành cùng sức khỏe phụ nữ',photoClass:'reference-photo',details:'Không gian giới thiệu dịch vụ chăm sóc sức khỏe phụ nữ và thai kỳ. Danh mục dịch vụ cụ thể sẽ được cập nhật sau khi bệnh viện xác nhận.'},
 {name:'Nhi khoa',desc:'Chăm sóc những mầm xanh tương lai',image:'adc8d1977f6d574e.png',details:'Đồng hành cùng ba mẹ trong chăm sóc sức khỏe trẻ em. Fanpage bệnh viện đã giới thiệu dịch vụ test nhanh hô hấp 7 trong 1 tại Khoa Nhi.'},
 {name:'Tai Mũi Họng',desc:'Chăm sóc sức khỏe, trọn vẹn giác quan',photoClass:'reference-photo ent',details:'Khu vực giới thiệu chuyên khoa theo bố cục demo. Vui lòng gọi bệnh viện để xác nhận lịch khám và dịch vụ.'},
 {name:'Chẩn đoán hình ảnh',desc:'Hỗ trợ chẩn đoán và theo dõi điều trị',image:'4c135fdb1e0c0e75.png',details:'Hình ảnh thực tế về hoạt động chụp X-quang được chia sẻ trên fanpage Đại An. Vui lòng liên hệ để được hướng dẫn trước khi thăm khám.'},
 {name:'Xét nghiệm',desc:'Thông tin cần thiết cho quá trình điều trị',image:'b89bed8cfcf32aa1.png',details:'Hình ảnh hoạt động lấy mẫu xét nghiệm tại Đại An. Các xét nghiệm và chi phí thực tế cần được xác nhận trực tiếp với bệnh viện.'},
 {name:'Ngoại khoa',desc:'Tận tâm trong từng bước điều trị',image:'641c18a1433a7a69.png',details:'Bệnh viện đang tuyển dụng bác sĩ Ngoại khoa theo thông báo trên fanpage. Liên hệ bệnh viện để được tư vấn dịch vụ và lịch khám.'},
 {name:'Tư vấn sức khỏe',desc:'Lắng nghe và hỗ trợ cùng bạn',image:'55d1223a1ac3ed1d.png',details:'Liên hệ hotline 0947 907 636 để được hướng dẫn lựa chọn chuyên khoa và chuẩn bị cho buổi khám.'}
];
const posts=[
 {id:'ho-hap',category:'health',label:'Thông tin sức khỏe',title:'Test nhanh hô hấp 7 trong 1: một lần lấy mẫu, kiểm tra nhiều tác nhân',image:'9005f84045d8d7a6.png',excerpt:'Đại An giới thiệu dịch vụ test nhanh hô hấp 7 trong 1, hỗ trợ quá trình thăm khám cho trẻ.',body:['Theo bài đăng trên fanpage, Bệnh viện Đa khoa Đại An triển khai bộ test nhanh hô hấp 7 trong 1 tại Khoa Nhi. Một lần lấy dịch mũi được sử dụng để kiểm tra các tác nhân được bài viết liệt kê: cúm A, cúm B, SARS-CoV-2, RSV, Adenovirus, HMPV và Mycoplasma pneumoniae.','Bài viết cũng giới thiệu hoạt động thăm khám và tư vấn của đội ngũ Nhi khoa. Phụ huynh có thể liên hệ hotline hoặc fanpage để được hướng dẫn phù hợp. Đây là bản tóm lược thông tin dịch vụ, không thay thế tư vấn của bác sĩ.'],url:'https://www.facebook.com/bvdkdaian/posts/pfbid02z6mYPrswEDBWEBvqQ2H1qDhcq8HsAdjnGH2CoqHWu2dQRhpbnATF7cxwrqXQPxUQl'},
 {id:'cong-dong',category:'community',label:'Hoạt động bệnh viện',title:'Đồng hành cùng địa phương, chung tay chăm sóc sức khỏe cộng đồng',image:'adc8d1977f6d574e.png',excerpt:'Những hình ảnh gần gũi trong hành trình chăm sóc sức khỏe cộng đồng được Đại An chia sẻ trên fanpage.',body:['Fanpage Bệnh viện Đa khoa Đại An chia sẻ bài viết với chủ đề đồng hành cùng địa phương và chung tay chăm sóc sức khỏe cộng đồng.','Bộ ảnh công khai ghi lại hoạt động thăm khám, đo huyết áp, lấy mẫu xét nghiệm và chụp X-quang. Mời bạn xem bài đăng gốc để theo dõi đầy đủ thông tin và hình ảnh của chương trình.'],url:'https://www.facebook.com/bvdkdaian/posts/pfbid02MMRb1q7R1YYU4E484o4DQGjC8WEQMyE9r5J2CR6dti3xVAAschTA9hXTpkm7KRaml'},
 {id:'tuyen-dung',category:'recruit',label:'Tuyển dụng',title:'Đại An chào đón bác sĩ Ngoại khoa cùng đồng hành và phát triển',image:'641c18a1433a7a69.png',excerpt:'Cơ hội làm việc trong môi trường y tế chuyên nghiệp, cùng đội ngũ tận tâm vì người bệnh.',body:['Bệnh viện Đa khoa Đại An thông báo tuyển dụng bác sĩ Ngoại khoa nhằm đáp ứng nhu cầu phát triển chuyên môn. Bài đăng nêu yêu cầu có chứng chỉ hành nghề theo quy định, ưu tiên ứng viên có trình độ Chuyên khoa I trở lên và kinh nghiệm phù hợp.','Ứng viên được giới thiệu cơ hội học tập, phát triển chuyên môn và chế độ thu nhập thỏa thuận theo năng lực. Hồ sơ tiếp nhận tại Phòng Thư ký, tầng 3, nhà điều hành của bệnh viện.','Thông tin liên hệ trong bài gốc: 0982 940 436 (chị Hà). Vui lòng kiểm tra bài đăng và liên hệ bệnh viện để xác nhận tình trạng tuyển dụng hiện tại.'],url:'https://www.facebook.com/bvdkdaian/posts/pfbid02SRrZ4DsothAMM6RtDFZaptHFHjVJo9AeKgqUoMCLdAR8n3X9V5wQAZLGQcUabNuZl'}
];
const quick=[['calendar','Đặt lịch trực tuyến','Chủ động, thuận tiện','book'],['file','Tra cứu kết quả','Thông tin khám, xét nghiệm','lookup'],['money','Bảng giá dịch vụ','Thông tin minh bạch','prices'],['book','Hướng dẫn khám bệnh','An tâm từ bước đầu','guide'],['shield','Bảo hiểm y tế','Hỗ trợ thủ tục','insurance'],['message','Góp ý – phản hồi','Lắng nghe để tốt hơn','feedback']];
document.querySelector('.quick-services').innerHTML=quick.map(([i,t,s,id])=>`<button class="quick-item" ${id==='book'?'data-book':`data-info="${id}"`}><span class="quick-icon">${icon(i)}</span><span><strong>${t}</strong><small>${s}</small></span><span class="arrow">${icon('arrow')}</span></button>`).join('');
function renderSpecialties(all=false){document.querySelector('#specialty-grid').innerHTML=specialties.slice(0,all?8:6).map((s,i)=>`<button class="specialty-card" data-specialty="${i}">${s.image?`<img class="specialty-photo" src="../assets/${s.image}" alt="Hình ảnh minh họa hoạt động ${s.name}" loading="lazy">`:`<div class="${s.photoClass}" role="img" aria-label="Ảnh minh họa ${s.name} từ mẫu thiết kế"></div>`}<div class="specialty-body"><h3>${s.name}</h3><p>${s.desc}</p><span class="card-arrow">${icon('arrow')}</span></div></button>`).join('');}
function renderNews(filter='all'){document.querySelector('#news-grid').innerHTML=posts.filter(p=>filter==='all'||p.category===filter).map(p=>`<article class="news-card"><button class="news-image-button" data-post="${p.id}" aria-label="Đọc bài: ${p.title}"><img src="../assets/${p.image}" alt="${p.title}" loading="lazy"></button><div class="news-body"><div class="news-meta"><b>${p.label}</b><span>Từ fanpage Đại An</span></div><h3><button class="news-title" data-post="${p.id}">${p.title}</button></h3><p>${p.excerpt}</p><button class="text-link" data-post="${p.id}">Đọc bài viết ${icon('arrow')}</button></div></article>`).join('');}
const modal=document.querySelector('#modal'), content=document.querySelector('#modal-content');let lastFocus;
function showModal(html){if(!modal.open){lastFocus=document.activeElement;modal.showModal();}content.innerHTML=html;document.body.classList.add('modal-open');modal.scrollTop=0;renderIcons(content);const focus=content.querySelector('input,select,button,a');if(focus)focus.focus();}
function closeModal(){modal.close();}
modal.addEventListener('close',()=>{document.body.classList.remove('modal-open');lastFocus?.focus();});
document.querySelector('.modal-close').addEventListener('click',closeModal);
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
function title(eyebrow,text){return `<p class="eyebrow modal-eyebrow">${eyebrow}</p><h2 id="modal-title">${text}</h2>`;}
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function booking(selected=''){showModal(`${title('ĐỒNG HÀNH CÙNG SỨC KHỎE CỦA BẠN','Đặt lịch khám')}<p class="modal-intro">Chọn chuyên khoa và thời gian phù hợp với bạn.</p><div class="demo-notice">Bản trình diễn: chỉ sử dụng thông tin giả để trải nghiệm. Dữ liệu không được lưu hoặc gửi đến bệnh viện.</div><form id="booking-form"><div class="form-grid"><label class="field">Họ và tên *<input name="name" required minlength="2" maxlength="80" autocomplete="off" placeholder="Nguyễn Văn An"></label><label class="field">Số điện thoại *<input name="phone" required type="tel" inputmode="tel" pattern="0[0-9]{9}" title="Nhập 10 chữ số, bắt đầu bằng 0" autocomplete="off" placeholder="0900000000"></label><label class="field">Chuyên khoa *<select name="specialty" required><option value="">Chọn chuyên khoa</option>${specialties.map(s=>`<option ${s.name===selected?'selected':''}>${s.name}</option>`).join('')}</select></label><label class="field">Ngày khám dự kiến *<input name="date" type="date" min="${localDate()}" required></label><label class="field full">Buổi khám<select name="session"><option>Buổi sáng</option><option>Buổi chiều</option></select></label></div><button class="button form-submit" type="submit">Trải nghiệm đặt lịch ${icon('arrow')}</button></form>`);document.querySelector('#booking-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(form.elements.date.value<localDate()){form.elements.date.setCustomValidity('Vui lòng chọn hôm nay hoặc một ngày trong tương lai.');form.elements.date.reportValidity();return;}const data=new FormData(form);const date=data.get('date').split('-').reverse().join('/');showModal(`<div class="success"><div class="success-icon">✓</div>${title('HOÀN TẤT TRẢI NGHIỆM','Bạn đã thử đặt lịch thành công')}<p>Chuyên khoa: <strong>${data.get('specialty')}</strong><br>${date} · ${data.get('session')}</p><div class="demo-notice">Đây là thông báo mô phỏng. Chưa có lịch khám thực tế được tạo và dữ liệu cá nhân không được lưu.</div><a class="button" href="tel:0947907636">Gọi đặt lịch thực tế: 0947 907 636</a></div>`);});document.querySelector('[name=date]').addEventListener('input',e=>e.target.setCustomValidity(''));}
function openPost(id){const p=posts.find(p=>p.id===id);if(!p)return;showModal(`${title(p.label,p.title)}<p class="source-note">Biên tập tóm lược từ fanpage Bệnh viện Đa khoa Đại An.</p><img class="article-image" src="../assets/${p.image}" alt="${p.title}"><div class="article-text">${p.body.map(t=>`<p>${t}</p>`).join('')}</div><a class="button article-source" href="${p.url}" target="_blank" rel="noopener">Xem bài viết gốc trên Facebook ↗</a>`);}
const info={guide:{title:'Hướng dẫn khám bệnh',body:'<ol class="info-list"><li>Liên hệ hotline hoặc fanpage để xác nhận lịch chuyên khoa.</li><li>Chuẩn bị giấy tờ tùy thân, thông tin BHYT và hồ sơ khám cũ nếu có.</li><li>Đến quầy tiếp đón để được hướng dẫn đăng ký.</li><li>Thăm khám và thực hiện các bước theo hướng dẫn của nhân viên y tế.</li><li>Nhận tư vấn và lịch tái khám nếu được chỉ định.</li></ol><p class="demo-notice">Quy trình minh họa cho bản demo; bệnh viện sẽ xác nhận hướng dẫn chính thức.</p>'},insurance:{title:'Hỗ trợ bảo hiểm y tế',body:'<p>Vui lòng chuẩn bị thông tin thẻ BHYT, giấy tờ tùy thân và giấy chuyển tuyến nếu có. Bộ phận tiếp đón sẽ kiểm tra và hướng dẫn các thủ tục phù hợp.</p><p>Phạm vi và mức hưởng phụ thuộc hồ sơ, dịch vụ và quy định áp dụng. Liên hệ bệnh viện để xác nhận trước khi khám.</p>'},prices:{title:'Thông tin giá dịch vụ',body:'<p>Bảng giá chính thức đang chờ bệnh viện cung cấp cho bản demo. Vui lòng liên hệ để được tư vấn mức phí của dịch vụ phù hợp.</p><ul class="info-list"><li>Khám chuyên khoa: liên hệ tư vấn</li><li>Xét nghiệm: liên hệ tư vấn</li><li>Chẩn đoán hình ảnh: liên hệ tư vấn</li><li>Gói khám sức khỏe: liên hệ tư vấn</li></ul>'}};
function openInfo(id){if(id==='lookup'){showModal(`${title('TIỆN ÍCH NGƯỜI BỆNH','Tra cứu kết quả')}<div class="demo-notice">Dữ liệu mẫu để trải nghiệm: mã <strong>DA-DEMO</strong>, số điện thoại <strong>0900000000</strong>. Không kết nối hồ sơ bệnh án.</div><form id="lookup-form"><div class="form-grid"><label class="field">Mã tra cứu<input name="code" required placeholder="DA-DEMO" autocomplete="off"></label><label class="field">Số điện thoại<input name="phone" required type="tel" placeholder="0900000000" autocomplete="off"></label></div><button class="button form-submit">Tra cứu ${icon('search')}</button></form><div id="lookup-result" role="status"></div>`);document.querySelector('#lookup-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);document.querySelector('#lookup-result').innerHTML=f.get('code').trim().toUpperCase()==='DA-DEMO'&&f.get('phone').trim()==='0900000000'?'<div class="result-panel"><strong>Hồ sơ trải nghiệm DA-DEMO</strong><p>Người bệnh: Khách hàng mẫu<br>Trạng thái: Hoàn tất quy trình minh họa</p>Không có kết quả xét nghiệm hoặc dữ liệu y tế thực tế trong bản demo.</div>':'<div class="result-panel">Không tìm thấy hồ sơ mẫu. Vui lòng dùng mã DA-DEMO và số 0900000000.</div>';});return;}
 if(id==='feedback'){showModal(`${title('LẮNG NGHE ĐỂ TỐT HƠN','Góp ý – phản hồi')}<div class="demo-notice">Biểu mẫu mô phỏng, không gửi và không lưu phản hồi. Bạn có thể liên hệ fanpage để gửi góp ý thực tế.</div><form id="feedback-form"><label class="field">Nội dung góp ý *<textarea required minlength="10" maxlength="1000" placeholder="Nhập ít nhất 10 ký tự để trải nghiệm…"></textarea></label><button class="button form-submit">Gửi thử phản hồi ${icon('arrow')}</button></form>`);document.querySelector('#feedback-form').addEventListener('submit',e=>{e.preventDefault();showModal(`${title('CẢM ƠN BẠN','Hoàn tất trải nghiệm góp ý')}<p>Phản hồi demo không được lưu hoặc gửi đi.</p><a class="button" href="https://www.facebook.com/bvdkdaian/" target="_blank" rel="noopener">Liên hệ fanpage ↗</a>`);});return;}
 const item=info[id];if(item)showModal(`${title('THÔNG TIN DÀNH CHO NGƯỜI BỆNH',item.title)}<div class="article-text">${item.body}</div><a class="button" href="tel:0947907636">${icon('phone')} Liên hệ 0947 907 636</a>`);}
function normalize(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();}
function search(){showModal(`${title('BẠN CẦN TÌM GÌ?','Tìm kiếm thông tin')}<input class="search-input" aria-label="Từ khóa tìm kiếm" placeholder="Tìm chuyên khoa, tin tức, dịch vụ…" type="search"><div class="search-results" aria-live="polite"></div>`);const input=content.querySelector('input'),result=content.querySelector('.search-results');function update(){const q=normalize(input.value.trim());const items=[...specialties.map((s,i)=>({title:s.name,kind:'Chuyên khoa',attr:`data-specialty="${i}"`})),...posts.map(p=>({title:p.title,kind:p.label,attr:`data-post="${p.id}"`}))].filter(x=>!q||normalize(x.title).includes(q));result.innerHTML=items.length?items.map(x=>`<button class="search-result" ${x.attr}><small>${x.kind}</small>${x.title}</button>`).join(''):'<p>Chưa có kết quả phù hợp. Thử “nhi”, “xét nghiệm” hoặc “tuyển dụng”.</p>';}input.addEventListener('input',update);update();}
document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;if(el.hasAttribute('data-book'))booking();if(el.dataset.info)openInfo(el.dataset.info);if(el.dataset.post)openPost(el.dataset.post);if(el.hasAttribute('data-recruit'))openPost('tuyen-dung');if(el.hasAttribute('data-search'))search();if(el.dataset.specialty!==undefined){const s=specialties[Number(el.dataset.specialty)];showModal(`${title('CHUYÊN KHOA ĐẠI AN',s.name)}<p class="article-text">${s.details}</p><p class="demo-notice">Giới thiệu dùng cho bản demo; hình ảnh mang tính minh họa. Lịch khám và dịch vụ cần được xác nhận với bệnh viện.</p><button class="button" id="specialty-book">${icon('calendar')} Đặt lịch chuyên khoa</button>`);document.querySelector('#specialty-book').addEventListener('click',()=>booking(s.name));}if(el.dataset.filter){document.querySelectorAll('[data-filter]').forEach(b=>{const active=b===el;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});renderNews(el.dataset.filter);}});
let all=false;document.querySelector('#all-specialties').addEventListener('click',e=>{all=!all;renderSpecialties(all);e.currentTarget.innerHTML=`${all?'Thu gọn':'Xem tất cả chuyên khoa'} ${icon('arrow')}`;});
const menu=document.querySelector('#menu-toggle'),nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'Đóng menu':'Mở menu');});nav.addEventListener('click',e=>{if(e.target.closest('a,button')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Mở menu');}});
document.querySelector('#back-top').addEventListener('click',()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}));
renderSpecialties();renderNews();renderIcons();
